apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  argocd/app-name: june13-test-6
  janus-idp.io/tekton: june13-test-6
  backstage.io/kubernetes-id: june13-test-6
  backstage.io/kubernetes-namespace: rhdh-app
  app.kubernetes.io/part-of: june13-test-6
resources:
  - initialize-namespace/
  - deployment.yaml
  - route.yaml
  - service.yaml
  - model-config.yaml
