apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/instance: june13-test-6
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: june13-test-6
  name: june13-test-6
spec:
  port:
    targetPort: 8501
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: june13-test-6
    weight: 100
  wildcardPolicy: None
