apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: june13-test-6-database
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: june13-test-6-database
  name: june13-test-6-database
spec:
  ports:
    - port: 
      protocol: TCP
      targetPort: 
  selector:
    app.kubernetes.io/instance: june13-test-6-database
